import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '1.1.0:0',
  releaseNotes: {
    en_US:
      "Empires 1.1.0 adds multiplayer. On the main menu choose Multiplayer: one player hosts and sets up the game — each seat Human or a computer — and shares a four-letter room code; the others join with it. Every player's game runs in step through this server. F3 pauses for everyone, Enter opens the chat, and a player whose connection drops rejoins within 30 seconds — after that a computer takes over their civilization. The Mac app joins by typing this server's address. Computer players also got better: their first Storage Pit goes to the forest, they put pits beside far hunts, forget prey that is gone, stop attacking what they can't reach and no longer pull builders into fights. On two-player island maps no villager starts stuck in a forest.",
    es_ES:
      'Empires 1.1.0 añade el multijugador. En el menú principal elige Multijugador: un jugador crea la partida y la configura —cada puesto Humano o de la computadora— y comparte un código de sala de cuatro letras; los demás se unen con él. La partida de cada jugador avanza a la par a través de este servidor. F3 pausa para todos, Intro abre el chat y quien pierde la conexión vuelve a entrar en 30 segundos; después, la computadora toma su civilización. La app de Mac se une escribiendo la dirección de este servidor. Los jugadores de la computadora también mejoran: su primer Almacén va al bosque, ponen almacenes junto a las cacerías lejanas, olvidan las presas que ya no están, dejan de atacar lo que no alcanzan y ya no sacan de sus obras a los constructores para pelear. En los mapas de islas para dos jugadores ningún aldeano empieza atrapado en un bosque.',
    de_DE:
      'Empires 1.1.0 bringt den Mehrspielermodus. Im Hauptmenü Mehrspieler wählen: Ein Spieler eröffnet die Partie und richtet sie ein — jeder Platz Mensch oder Computer — und teilt einen vierstelligen Raumcode; die anderen treten damit bei. Die Partien aller Spieler laufen über diesen Server im Gleichschritt. F3 pausiert für alle, Enter öffnet den Chat, und wer die Verbindung verliert, kehrt binnen 30 Sekunden zurück — danach übernimmt der Computer seine Zivilisation. Die Mac-App tritt bei, indem man die Adresse dieses Servers eingibt. Auch die Computerspieler wurden besser: Ihre erste Lagergrube steht am Wald, sie bauen Gruben neben ferne Jagdgründe, vergessen verschwundene Beute, greifen nichts Unerreichbares mehr an und holen Bauarbeiter nicht mehr in Kämpfe. Auf Inselkarten für zwei Spieler beginnt kein Dorfbewohner mehr eingeschlossen im Wald.',
    pl_PL:
      'Empires 1.1.0 dodaje grę wieloosobową. W menu głównym wybierz Gra wieloosobowa: jeden gracz zakłada grę i ją ustawia — każde miejsce Człowiek albo komputer — i podaje czteroliterowy kod pokoju; pozostali dołączają z jego pomocą. Gry wszystkich graczy idą równo przez ten serwer. F3 wstrzymuje grę wszystkim, Enter otwiera czat, a gracz, któremu zerwie się połączenie, wraca w ciągu 30 sekund — potem jego cywilizację przejmuje komputer. Aplikacja na Maca dołącza po wpisaniu adresu tego serwera. Gracze komputerowi też są lepsi: pierwszy Magazyn stawiają przy lesie, budują magazyny obok dalekich polowań, zapominają o zwierzynie, której już nie ma, nie atakują tego, czego nie mogą dosięgnąć, i nie odciągają budowniczych do walki. Na mapach wysp dla dwóch graczy żaden osadnik nie zaczyna uwięziony w lesie.',
    fr_FR:
      'Empires 1.1.0 ajoute le multijoueur. Dans le menu principal, choisissez Multijoueur : un joueur crée la partie et la règle — chaque place Humain ou ordinateur — puis partage un code de salle de quatre lettres ; les autres le rejoignent avec ce code. La partie de chacun avance au même pas grâce à ce serveur. F3 met en pause pour tous, Entrée ouvre la discussion, et un joueur qui perd la connexion revient dans les 30 secondes — passé ce délai, l’ordinateur prend sa civilisation. L’application Mac rejoint en tapant l’adresse de ce serveur. Les joueurs ordinateur progressent aussi : leur première Fosse de stockage va à la forêt, ils en bâtissent près des chasses lointaines, oublient le gibier disparu, n’attaquent plus ce qu’ils ne peuvent atteindre et n’arrachent plus les bâtisseurs à leur chantier pour combattre. Sur les cartes d’îles à deux joueurs, aucun villageois ne commence coincé dans une forêt.',
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
