import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '1.0.1:0',
  releaseNotes: {
    en_US:
      "Empires 1.0.1, a polish release. Fairer starts: on Narrows nobody starts in the strait and teams share a side; crowded island and land maps no longer bury villagers in forest or strip an island bare; two players on Coastal stand the same distance from the sea; teammates on Large Islands, and neighbours on Mediterranean and Narrows, can walk to each other; land starts keep their own gold and stone. Computer players keep room for an army at the default population, finish the fields they lay out, build only where their villagers can walk, and stop chasing what they cannot reach; Nomad computers always found a Town Center, in a Death Match game they age up at once, and with a population limit above 50 they raise armies to match. Towers can be told which unit to shoot, a catapult on Stand Ground holds its fire, and a big group of elephants sent through a gap no longer leaves some behind. Unit details now include civilization bonuses and technologies; tooltips are no longer cut off, and a technology's tooltip says what it does. Escape closes the window on top, keys no longer reach the game behind a menu, and Backspace never leaves the game. Two players saving to the server at once no longer clash. Games saved with 1.0.0 still load.",
    es_ES:
      'Empires 1.0.1, una versión de pulido. Comienzos más justos: en Estrechos nadie empieza en el estrecho y cada equipo comparte una orilla; los mapas de islas y de tierra con muchos jugadores ya no entierran aldeanos en el bosque ni dejan una isla vacía; dos jugadores en Costero quedan a la misma distancia del mar; los aliados en Islas Grandes, y los vecinos en Mediterráneo y Estrechos, pueden llegar a pie unos a otros; los comienzos en tierra conservan su propio oro y piedra. Los jugadores de la computadora guardan sitio para un ejército con la población predeterminada, terminan los campos que trazan, construyen solo donde sus aldeanos pueden llegar y dejan de perseguir lo que no alcanzan; en Nómada siempre fundan un Centro Urbano, en Combate a muerte avanzan de edad enseguida y, con un límite de población superior a 50, reúnen ejércitos acordes. Se puede indicar a las torres a qué unidad disparar, una catapulta en Mantener posición no dispara y un grupo grande de elefantes enviado por un paso ya no deja a algunos atrás. Los datos de las unidades incluyen las bonificaciones de la civilización y las tecnologías; los consejos emergentes ya no se cortan, y el de una tecnología dice lo que hace. Escape cierra la ventana de arriba, las teclas ya no llegan a la partida detrás de un menú y Retroceso nunca abandona la partida. Dos jugadores que guardan en el servidor a la vez ya no chocan. Las partidas guardadas con la 1.0.0 siguen cargándose.',
    de_DE:
      'Empires 1.0.1, eine Feinschliff-Version. Gerechtere Starts: Auf Meerenge beginnt niemand in der Meerenge, und Teams teilen sich ein Ufer; volle Insel- und Landkarten begraben keine Dorfbewohner mehr im Wald und lassen keine Insel leer; zwei Spieler auf Küste stehen gleich weit vom Meer; Verbündete auf Großen Inseln sowie Nachbarn auf Mittelmeer und Meerenge erreichen einander zu Fuß; Landstarts behalten ihr eigenes Gold und ihren Stein. Computerspieler lassen bei der Standardbevölkerung Platz für ein Heer, bestellen die Felder, die sie anlegen, bauen nur, wo ihre Dorfbewohner hinkommen, und verfolgen nicht mehr, was sie nicht erreichen; als Nomaden gründen sie stets ein Dorfzentrum, im Todeskampf steigen sie sofort im Zeitalter auf, und bei einem Bevölkerungslimit über 50 stellen sie entsprechend größere Heere auf. Türmen lässt sich ein Ziel zuweisen, ein Katapult auf Stellung halten feuert nicht von selbst, und eine große Elefantengruppe, die durch eine Lücke geschickt wird, lässt keine Tiere mehr zurück. Die Einheitenwerte zeigen Zivilisationsboni und Technologien; Tooltips werden nicht mehr abgeschnitten, und der Tooltip einer Technologie sagt, was sie bewirkt. Escape schließt das oberste Fenster, Tasten erreichen das Spiel hinter einem Menü nicht mehr, und die Rücktaste verlässt das Spiel nie. Zwei Spieler, die gleichzeitig auf dem Server speichern, kommen sich nicht mehr in die Quere. Spielstände aus 1.0.0 lassen sich weiterhin laden.',
    pl_PL:
      'Empires 1.0.1, wydanie szlifujące. Uczciwsze starty: na mapie Cieśnina nikt nie zaczyna w cieśninie, a drużyny dzielą jeden brzeg; zatłoczone mapy wysp i lądowe nie zakopują już osadników w lesie ani nie zostawiają pustej wyspy; dwóch graczy na mapie Wybrzeże stoi równie daleko od morza; sojusznicy na Dużych Wyspach oraz sąsiedzi na mapach Śródziemnomorska i Cieśnina mogą do siebie dojść; starty lądowe zachowują własne złoto i kamień. Gracze komputerowi zostawiają miejsce na armię przy domyślnej populacji, kończą wytyczone pola, budują tylko tam, dokąd dojdą ich osadnicy, i nie gonią tego, czego nie mogą dosięgnąć; w trybie Nomadów zawsze zakładają Centrum Miasta, w Walce na śmierć od razu przechodzą do kolejnej epoki, a przy limicie populacji powyżej 50 wystawiają odpowiednio większe armie. Wieżom można wskazać cel, katapulta w trybie Utrzymaj pozycję nie strzela sama, a duża grupa słoni wysłana przez przejście nie zostawia już nikogo w tyle. Dane jednostek uwzględniają premie cywilizacji i technologie; podpowiedzi nie są już ucinane, a podpowiedź technologii mówi, co ona daje. Escape zamyka okno na wierzchu, klawisze nie trafiają już do gry za menu, a Backspace nigdy nie opuszcza gry. Dwóch graczy zapisujących na serwerze jednocześnie już sobie nie przeszkadza. Gry zapisane w 1.0.0 nadal się wczytują.',
    fr_FR:
      'Empires 1.0.1, une version de finition. Des départs plus justes : sur Détroit, personne ne commence dans le détroit et chaque équipe partage une rive ; les cartes d’îles et terrestres très peuplées n’enterrent plus de villageois dans la forêt et ne laissent plus d’île nue ; deux joueurs sur Côtière se tiennent à la même distance de la mer ; les alliés sur Grandes Îles, et les voisins sur Méditerranée et Détroit, peuvent se rejoindre à pied ; les départs terrestres gardent leur or et leur pierre. Les joueurs ordinateur gardent de la place pour une armée à la population par défaut, achèvent les champs qu’ils tracent, ne bâtissent que là où leurs villageois peuvent aller et cessent de poursuivre ce qu’ils ne peuvent atteindre ; en Nomade, ils fondent toujours un Centre-ville, en Combat à mort ils changent d’âge sans attendre, et avec une limite de population au-delà de 50 ils lèvent des armées à la mesure. On peut désigner aux tours l’unité à viser, une catapulte en Tenir la position ne tire plus d’elle-même et un grand groupe d’éléphants envoyé par un passage n’en laisse plus en arrière. Les caractéristiques des unités incluent les bonus de civilisation et les technologies ; les infobulles ne sont plus tronquées et celle d’une technologie dit ce qu’elle fait. Échap ferme la fenêtre du dessus, les touches n’atteignent plus la partie derrière un menu et Retour arrière ne quitte jamais la partie. Deux joueurs qui sauvegardent sur le serveur en même temps ne se gênent plus. Les parties sauvegardées avec la 1.0.0 se chargent toujours.',
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
